from __future__ import annotations

# ============================================================
# 🏀 NBA Analytics v4 — Streamlit Dashboard
# File: src/dashboard/app.py
#
# Description:
#     Simple UI to view today's combined predictions:
#       - Moneyline win probability
#       - Predicted total points
#       - Predicted spread margin
#
#     Reads:
#       data/predictions_combined/combined_<date>.parquet
# ============================================================

import streamlit as st
import pandas as pd
from datetime import date
from pathlib import Path

from src.config.paths import COMBINED_PRED_DIR


# ------------------------------------------------------------
# Helpers
# ------------------------------------------------------------


def load_combined_predictions(pred_date: date) -> pd.DataFrame:
    """
    Load combined predictions for pred_date.
    """
    path = COMBINED_PRED_DIR / f"combined_{pred_date}.parquet"
    if not path.exists():
        st.warning(f"No combined predictions found for {pred_date}.")
        return pd.DataFrame()

    df = pd.read_parquet(path)
    df["date"] = pd.to_datetime(df["date"])
    return df


# ------------------------------------------------------------
# Streamlit UI
# ------------------------------------------------------------


def main():
    st.set_page_config(
        page_title="NBA Analytics v4 — Daily Predictions",
        layout="wide",
        initial_sidebar_state="expanded",
    )

    st.title("🏀 NBA Analytics v4 — Daily Predictions Dashboard")
    st.markdown(
        """
        This dashboard displays **today’s combined predictions** generated by the v4 pipeline:
        - **Moneyline win probability**
        - **Predicted total points**
        - **Predicted spread margin**
        """
    )

    # --------------------------------------------------------
    # Date selector
    # --------------------------------------------------------
    today = date.today()
    pred_date = st.sidebar.date_input("Prediction Date", today)

    # --------------------------------------------------------
    # Load predictions
    # --------------------------------------------------------
    df = load_combined_predictions(pred_date)

    if df.empty:
        st.stop()

    # --------------------------------------------------------
    # Sidebar filters
    # --------------------------------------------------------
    st.sidebar.header("Filters")

    teams = sorted(set(df["home_team"]).union(df["away_team"]))
    team_filter = st.sidebar.multiselect("Filter by Team", teams)

    min_prob = st.sidebar.slider(
        "Minimum Home Win Probability",
        min_value=0.0,
        max_value=1.0,
        value=0.0,
        step=0.01,
    )

    # --------------------------------------------------------
    # Apply filters
    # --------------------------------------------------------
    filtered = df.copy()

    if team_filter:
        filtered = filtered[
            filtered["home_team"].isin(team_filter)
            | filtered["away_team"].isin(team_filter)
        ]

    if "win_probability" in filtered.columns:
        filtered = filtered[filtered["win_probability"] >= min_prob]

    # --------------------------------------------------------
    # Display table
    # --------------------------------------------------------
    st.subheader(f"Predictions for {pred_date}")

    # Reorder columns for readability
    preferred_cols = [
        "game_id",
        "home_team",
        "away_team",
        "win_probability",
        "predicted_total_points",
        "predicted_margin",
        "model_type",
        "model_version",
    ]

    cols = [c for c in preferred_cols if c in filtered.columns] + [
        c for c in filtered.columns if c not in preferred_cols
    ]

    st.dataframe(filtered[cols], use_container_width=True)

    # --------------------------------------------------------
    # Summary metrics
    # --------------------------------------------------------
    st.markdown("---")
    st.subheader("Summary")

    if "win_probability" in filtered.columns:
        st.metric(
            "Average Home Win Probability",
            f"{filtered['win_probability'].mean():.3f}",
        )

    if "predicted_total_points" in filtered.columns:
        st.metric(
            "Average Predicted Total Points",
            f"{filtered['predicted_total_points'].mean():.1f}",
        )

    if "predicted_margin" in filtered.columns:
        st.metric(
            "Average Predicted Spread Margin",
            f"{filtered['predicted_margin'].mean():.1f}",
        )


if __name__ == "__main__":
    main()
