from src.config.paths import (
    SCHEDULE_SNAPSHOT,
    MODEL_REGISTRY_DIR,
    DATA_DIR,
    CANONICAL_DIR,
    FEATURES_DIR,
    PREDICTIONS_DIR,
    TOTALS_PRED_DIR,
    SPREAD_PRED_DIR,
    COMBINED_PRED_DIR,
)